### ISSUE TITLE
support us with the checkpoint of the large whisper model that is finetuned in MGB2 dataset 

### ISSUE THREAD

**Issue by Body123** [ARBML/whisper_sprint#1]

**Comment by zaidalyafeai** [comment]
All checkpoints are on huggingface https://huggingface.co/arbml/whisper-largev2-ar

**Comment by Body123** [comment]
thanks a lot 
![4](https://user-images.githubusercontent.com/24945076/209471324-949742ae-30ed-4e58-9de8-639725374645.jpg)
I try to inference the model by this way in the picture but it take me a much time to get the output is any way to make the inference fast . or you recommend inference in another way to make it faster .
in comparison to inference the model from  repository of whisper that is much faster (! pip install git+https://github.com/openai/whisper.git -q)

**Comment by Body123** [comment]
okey thanks alot
