### ISSUE TITLE
I think large version checkpoint same as medium checkpoint 

### ISSUE THREAD

**Issue by Body123** [ARBML/whisper_sprint#2]

**Comment by zaidalyafeai** [comment]
Why do you think that?

**Comment by Body123** [comment]
the original checkpoint for large from openAI is 6 GB and from you is only 3 GB same as the medium you support 3GB also

**Comment by zaidalyafeai** [comment]
The two checkpoints seem different one 3.06 and the other 3.09. We are using deepspeed for training the large model, so maybe that is the reason. Still have to make sure, though.
