### ISSUE TITLE
Asking about License

### ISSUE THREAD

**Issue by Body123** [ARBML/whisper_sprint#3]
to use arbml/whisper-largev2-ar its license is License:
apache-2.0 so it can be used in commercial products 
but I think that MGB2 dataset (that the model finetuned  with it ) is for research is there any conflict about that

**Comment by zaidalyafeai** [comment]
As far as I understand the dataset licenses dont carry to pretrained models. There are hundreds of models that are trained on copyrighted materials.

**Comment by malmarz** [comment]
I would also check the mgb2 license before you reach a conclusion that it doesn't carryover... just in case
